name: zenit_window_plugin
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.2.0-87.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaru_window: ^0.1.3
  zenit_ui: 
    path: ../zenit_ui
  handy_window:
    path: ../../stuff/handy_window.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

